baseURL: https://wyatt-johnston.com
languageCode: en-us
title: Wyatt Johnston
theme: PaperMod
publishDir: "docs"
canonifyURLs: true

defaultContentLanguage: en
hasCJKLanguage: true

pagination:
  paperSize: 4

googleAnalytics: G-WN3L3N0N7J

# =============================
# Menu
# =============================
menu:
  main:
    - name: About
      url: /
      weight: 1

    - name: Blog
      url: /blog/
      weight: 2
    
    - name: Research
      url: /research/
      weight: 2.5

    - name: Projects
      url: /projects/
      weight: 3

    - name: Crossword
      url: /crossword/
      weight: 4

    - name: Tutoring
      url: /tutoring/
      weight: 5

    - name: CV
      url: "/cv.pdf"
      weight: 6

# =============================
# Markup
# =============================
markup:
  highlight:
    guessSyntax: true
    style: emacs
  goldmark:
    renderer:
      unsafe: true
      extensions:
        passthrough:
          enable: true
          delimiters:
            block:
              - ['$$', '$$']
            inline:
              - ['$', '$']

# =============================
# PaperMod Parameters
# =============================
params:
  author: Wyatt Johnston
  description: "PhD Student in ORIE @ UT Austin"
  hideAuthor: true

  label:
    text: Wyatt Johnston
    icon: "favicon.ico"
    iconHeight: 44

  # Home page behavior
  disableSpecial1stPost: true
  hideSummary: true
  showRecentPosts: false

  # UI / Layout
  showToc: false
  math: true
  showReadingTime: false
  showBreadCrumbs: false
  showCodeCopyButtons: true
  defaultTheme: "light"

  # Footer
  showPoweredBy: false
  copyright: ""

  # Profile (optional; nice for About page)
  profileMode:
    enabled: false

  # Social icons (PaperMod style)
  socialIcons:
    - name: "github"
      url: "https://github.com/wyattj37"
    - name: "linkedin"
      url: "https://linkedin.com/in/wyatt-d-johnston"
    - name: "email"
      url: "mailto:wyattdj2@illinois.edu"

  # Assets
  assets:
    disableHLJS: true
    favicon: "favicon.ico"

  # Custom CSS / JS
  customCSS:
    # - css/custom.css
  customJS:
    # - js/custom.js
